### ISSUE TITLE
issues importing in python3

### ISSUE THREAD

**Issue by seth-a** [dfm/python-nufft#9]
I don't see python3 support or lack of support mentioned anywhere, although that may be the root of this problem.  In any case, I can import and use nufft with no problems in python2.7, but running in python3 gives the following error.  Any suggestions how to fix this are appreciated.
```

Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nufft
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nufft/__init__.py", line 21, in <module>
    from .nufft import nufft1d1freqs, nufft1d1, nufft1d2, nufft1d3, nufft2d1, nufft2d2, nufft2d3, nufft3d1, nufft3d2, nufft3d3
  File "/usr/local/lib/python2.7/dist-packages/nufft/nufft.py", line 18, in <module>
    from ._nufft import (
ImportError: /usr/local/lib/python2.7/dist-packages/nufft/_nufft.so: undefined symbol: PyCObject_Type

```

**Comment by seth-a** [comment]
And fixed it.  I had to remove the files put in place by "python setup.py install", then ran "python3 setup.py install".
